Update demo gatsby media
tinacms/tinacms pull request #1540
Opened 2020-10-08 21:04 UTC by kendallstrautman

Updates the demo to work with latest media changes. I had to adjust the way the selected media preview src was being generated with wysiwyg images to account for promises. 

Also, a small style fix in the media manager.

2020-10-10 00:15 UTC, kendallstrautman commented
@ncphillips just needed the extra .3rem 😅

2020-10-12 16:04 UTC, kendallstrautman commented
@all-contributors please add @kud for docs

2020-10-12 16:32 UTC, dwalkr requested changes

2020-10-12 16:32 UTC, dwalkr commented on packages/demo-gatsby/src/templates/blog-post.js
> +                  const postPathParts = blogPost.fileRelativePath.split("/")
could replace this whole function w/ a call to `path.dirname` https://nodejs.org/api/path.html#path_path_dirname_path

2020-10-12 16:32 UTC, dwalkr commented on packages/demo-gatsby/src/templates/blog-post.js
> +                  const formattedSrc = src.replace(/\/public|\/static/, "")
```suggestion
                  const formattedSrc = src.replace(/^\/public|\/static/, "")
```

2020-10-12 17:02 UTC, dwalkr approved these changes

2020-10-12 17:22 UTC, merged