fix(react-tinacms-editor): fixes menu jumping to top on scroll
tinacms/tinacms pull request #1549
Opened 2020-10-13 21:18 UTC by kendallstrautman

closes #1495

2020-10-13 21:20 UTC, kendallstrautman commented on packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx
> +        setMenuStartPos(wysiwygWrapper?.getBoundingClientRect().top)
```suggestion
        setMenuStartPos(wysiwygWrapper.getBoundingClientRect().top)
```

2020-10-13 21:43 UTC, DirtyF submitted a review, later dismissed
It's not jumping anymore, yeah!

Bonus points: Could we achieve a smoother transition here but make the toolbar sticky a bit earlier? 
https://www.loom.com/share/c738699dcc1847c3a38b55a45f208f48

2020-10-13 22:55 UTC, kendallstrautman commented
Oh yeah it's not taking into account the toolbar offset. I'll look into that

2020-10-14 00:08 UTC, kendallstrautman commented on packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx
> +
```suggestion
```

2020-10-14 19:19 UTC, kendallstrautman commented
@all-contributors please add @franknoirot for docs

2020-10-14 20:32 UTC, dwalkr commented on packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx
> +    if (el.offsetParent) {
```
while (el.offsetParent) {
//...
}
```

2020-10-14 20:43 UTC, dwalkr commented on packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx
> +  function getOffsetTop(el: any) {
we should move this outside of the component body

2020-10-14 20:52 UTC, dwalkr commented on packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx
> +    const stickyTopOffset = parseInt(menuFixedTopOffset.replace(/px$/, ''))
```suggestion
    const stickyTopOffset = parseInt(menuFixedTopOffset, 10)
```

2020-10-14 21:38 UTC, DirtyF approved these changes
Soooo much better, awesome work @kendallstrautman 👍

2020-10-15 13:27 UTC, dwalkr commented
I'm still seeing the title bar flicker in the next demo on Chrome

2020-10-15 14:43 UTC, DirtyF commented
It's almost OK on my end when I add the sticky prop 
https://www.loom.com/share/4aeae82a474d41a49b267580e6e54f96

There's one glitch when you scroll down past the editor. Maybe a border / focus ring thing?

2020-10-15 15:14 UTC, dwalkr commented
it's not working at all for me.

![editmodebrowserext](https://user-images.githubusercontent.com/15221702/96149605-83fbb200-0ed7-11eb-9cfd-0d83a3a3df80.gif)

2020-10-15 15:32 UTC, DirtyF commented
Right, when the WYSIWYG is positioned in the bottom it does not follow the scroll, and I don't manage to set sticky `true` 🤷

2020-10-15 15:32 UTC, kendallstrautman commented
yeah something went wrong. I've been testing on /blog/apple but i'll try to see whats up

2020-10-15 21:32 UTC, DirtyF commented
@kendallstrautman Agreed,  it's weird to have to pass the CSS variables of the toolbar height to the sticky prop. If the toolbar is here, sticky true should be visible by default.

Do we have a way to define a low priority to load the toolbar, like can it be done only when you cick in the wysiwyg field? I feel this issue is opening some rabbit hole on how to better smart load that toolbar.

2020-10-15 22:35 UTC, kendallstrautman commented
That's a great point @DirtyF. I feel like there's a broader UX discussion here of _how_ we want the wysiwyg menubar (toolbar) to behave. I like the idea of it only showing up on click. First I need to suss out this sticky `offset` logic, but I think we could investigate your other points in another PR.

2020-10-17 00:25 UTC, kendallstrautman commented
This is ready for another look @DirtyF & @dwalkr. I debounced the scroll event handlers to try and smooth things out and contained the layout calculations for whether the menu should stick or not in a `requestAnimationFrame`. I also delayed the offset calculation until the the whole page (with images) finished loading. I tested on the info page and it seems to work as expected, but please do some digging. 

One last thing that would be nice is to programmatically handle the toolbar height in the offset calculation. That would require us knowing whether the toolbar was mounted and it felt like another PR.

2020-10-18 11:33 UTC, DirtyF approved these changes
- This is better on demo-next package 🎉 
- Didn't manage to see the update on demo-gatsby 🤷 (pebkac,)
- `Sticky` does not seem to work in Safari 🧭 (https://caniuse.com/css-sticky: A parent with overflow set to auto will prevent position: sticky from working in Safari )

2020-10-23 20:20 UTC, dwalkr requested changes
@kendallstrautman while testing this out on the next demo I found the sizing of the floating menu to be a little glitchy - it would often show up at first as too small.

While looking into the problem I ended up with a fix that cuts out a lot of code, so I made a separate PR into this branch that I'd like you to look at https://github.com/tinacms/tinacms/pull/1569

2020-10-25 08:51 UTC, jpuri commented on packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx
Function to calculate offsetTop is already in utils: https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-editor/src/utils.ts#L21

2020-10-25 11:30 UTC, jpuri commented
Hey @kendallstrautman : changes look good, but as I checked these in demo gatsby, they are still not addressing all scenario.

![sticky_menu](https://user-images.githubusercontent.com/2182307/97105771-8a620900-16e3-11eb-8545-7fc6ac2dd72a.gif)

@spbyrne : implemented previous version of sticky menu and has also context about it.

2020-10-26 21:09 UTC, kendallstrautman commented
Thanks @DirtyF & @jpuri I'll check this out on demo-gatsby and use that offsetTop from the utils!

2020-10-28 01:16 UTC, jpuri approved these changes
Good work 👍

2020-10-28 14:42 UTC, dwalkr commented
For the record, I am still seeing the sizing issue, but it's not shrinking as much as it was before:

![menubar-sizing](https://user-images.githubusercontent.com/15221702/97451335-0b024e80-190a-11eb-8d6f-b75c1cc42ab6.gif)

With that said, this looks pretty minor now and is a significant improvement over the previous buggy jumping. I don't think we need to flog this horse any more :smile:

2020-10-28 14:43 UTC, dwalkr approved these changes

2020-10-28 14:57 UTC, merged