fix(react-tinacms-github): added action.name as key prop in actions.m…
tinacms/tinacms pull request #1559
Opened 2020-10-18 21:43 UTC by dangayle

added action.name as key prop in actions.map method

fix https://github.com/tinacms/tinacms/issues/1557

2020-10-18 21:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tinacms/tinacms?pullRequest=1559) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tinacms/tinacms?pullRequest=1559) before we can accept your contribution.<br/><hr/>**Dan Gayle** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tinacms/tinacms?pullRequest=1559) it.</sub>

2020-10-20 13:57 UTC, dwalkr requested changes

2020-10-20 13:57 UTC, dwalkr commented on packages/react-tinacms-github/src/components/ActionableModal.tsx
> +                key="name"
key should not be a constant https://reactjs.org/docs/lists-and-keys.html#keys

2020-10-20 18:46 UTC, dangayle commented
Oh god, what a noob mistake. I will fix.

On Tue, Oct 20, 2020 at 6:57 AM DJ <notifications@github.com> wrote:

> *@dwalkr* requested changes on this pull request.
> ------------------------------
>
> In packages/react-tinacms-github/src/components/ActionableModal.tsx
> <https://github.com/tinacms/tinacms/pull/1559#discussion_r508528249>:
>
> > @@ -50,8 +50,12 @@ export const ActionableModal = ({
>              <p>{message}</p>
>            </ModalBody>
>            <ModalActions>
> -            {actions.map(action => (
> -              <TinaButton primary={action.primary} onClick={action.action}>
> +            {actions.map((action) => (
> +              <TinaButton
> +                key="name"
>
> key should not be a constant
> https://reactjs.org/docs/lists-and-keys.html#keys
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tinacms/tinacms/pull/1559#pullrequestreview-512745600>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA7US5OOKV4AO5LMLV32XLSLWJM5ANCNFSM4SVLQIKQ>
> .
>

2020-10-21 14:03 UTC, dwalkr commented
@dangayle FYI we also need contributors to this project to sign the Contributor License Agreement. It looks the commits in this PR aren't tied to your GitHub user. In order for CLAassistant to approve this, all committers need to be tied to GitHub.

You can fix this by setting a user email for git that matches an email associated with your GitHub account: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git

You will then need to amend + force push your current commit to replace the author.

Sorry for making this so complicated, but once you set this up it shouldn't be an issue in the future!

2020-10-21 16:24 UTC, dangayle commented
Yeah, I did the CLA, but didn’t know I needed to amend the push. I’ll do
that. Thank you for your patience.

On Wed, Oct 21, 2020 at 7:03 AM DJ <notifications@github.com> wrote:

> @dangayle <https://github.com/dangayle> FYI we also need contributors to
> this project to sign the Contributor License Agreement. It looks the
> commits in this PR aren't tied to your GitHub user. In order for
> CLAassistant to approve this, all committers need to be tied to GitHub.
>
> You can fix this by setting a user email for git that matches an email
> associated with your GitHub account:
> https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git
>
> You will then need to amend + force push your current commit to replace
> the author.
>
> Sorry for making this so complicated, but once you set this up it
> shouldn't be an issue in the future!
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/tinacms/tinacms/pull/1559#issuecomment-713601264>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA7USYKE3XHHUZ44FHYEGTSL3S4BANCNFSM4SVLQIKQ>
> .
>

2021-02-02 15:59 UTC, dwalkr commented
@dangayle I'm gonna close this PR as it's been open with no activity for a little while. You're welcome to reopen it if/when you're ready to come back to it!

2021-02-02 15:59 UTC, closed without merging