feat(tinacms): Video support for media manager, inline forms and fields
tinacms/tinacms pull request #1581
Opened 2020-10-29 23:28 UTC by jc-delvalle

2020-10-29 23:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tinacms/tinacms?pullRequest=1581) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tinacms/tinacms?pullRequest=1581) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tinacms/tinacms?pullRequest=1581) it.</sub>

2020-10-30 07:25 UTC, DirtyF commented
@jc-delvalle Could you share more of your context use here? What do you wish to accomplish with videos?

2020-10-30 15:06 UTC, jc-delvalle commented
Sure, we need to be able to edit videos just as images. So what I added was same functionality as inline images so you are able to add an InlineVideo component and edit its content using the media manager and the fields components. The only changes to the media manager are to be able to upload video/* and filter the list depending on what component you are coming from ( Image/Video ). 

Some content may also have video as background, you should be able to change that video source from the Edit form.

2020-10-30 15:38 UTC, kendallstrautman commented
Hey @jc-delvalle! Thanks so much for making this PR, this is awesome. 🎉 I'm sure lots of folks will find these fields useful.

In order to make it easier to review this work, could you rebase this into smaller, more defined commits using the [conventional commit naming](https://github.com/tinacms/tinacms/blob/master/CONTRIBUTING.md#making-commits)? 

We do this so we can generate changelogs for each package accordingly and have a better track of how different packages are affected by each change. Additionally, it helps us keep track of when we need to update package READMEs or add new documentation. 

Another thing that would really help us test this PR would be adding a test case in `demo-next` and `demo-gatsby`, as we need to verify that this works with both. Thanks again!

2020-10-30 15:41 UTC, kendallstrautman requested changes
Hey @jc-delvalle! Thanks so much for making this PR, this is awesome. 🎉 I'm sure lots of folks will find these fields useful.

In order to make it easier to review this work, could you rebase this into smaller, more defined commits using the [conventional commit naming](https://github.com/tinacms/tinacms/blob/master/CONTRIBUTING.md#making-commits)?

We do this so we can generate changelogs for each package accordingly and have a better track of how different packages are affected by each change. Additionally, it helps us keep track of when we need to update package READMEs or add new documentation.

Another thing that would really help us test this PR would be adding test cases in demo-next and demo-gatsby, as we need to verify that this works with both. And if you could provide some general explanation and upfront examples of how the new changes being introduced work in your PR description, that makes the whole process smoother. Thanks again!

2020-10-30 16:36 UTC, jc-delvalle commented
Ok, will try to do that this weekend and break down code into more commits. Will comment here when its done.

2020-11-03 23:00 UTC, jc-delvalle commented
@kendallstrautman @DirtyF I added more detailed commits and a test implementation on demo-next. You'r feedback will be appreciated.

2020-11-05 16:29 UTC, DirtyF commented
This is breaking existing media-stores:

```
Error: /Users/frank/github/tina/tinacms/packages/@tinacms/git-client/src/git-media-store.ts(48,9): semantic error TS2322: Type '"file"' is not assignable to type '"image" | "video" | "dir"'.
```

2020-11-08 23:14 UTC, chrisdmacrae commented
> This is breaking existing media-stores:
> 
> ```
> Error: /Users/frank/github/tina/tinacms/packages/@tinacms/git-client/src/git-media-store.ts(48,9): semantic error TS2322: Type '"file"' is not assignable to type '"image" | "video" | "dir"'.
> ```

@jc-delvalle IMHO, don't do a breaking change here. Type should be:

```
"file" | "image" | "video" | "dir"
```

File being a "generic" fallback for any non-special format.

2020-11-09 23:18 UTC, jc-delvalle commented
Ok @chrisdmacrae, that makes sense, I'll do the change and update the PR.

2020-11-11 00:34 UTC, jc-delvalle commented
@chrisdmacrae, I added the generic 'file' type to media manager so it doesn't break current media sources

2020-11-12 23:33 UTC, kendallstrautman commented on packages/react-tinacms-inline/src/blocks/inline-block-video.tsx
> + * @deprecated
This looks like a copy / paste of other deprecated block field files. We can delete this file and just recommend folks use `InlineVideo` from the start.

2020-11-12 23:37 UTC, kendallstrautman commented on packages/tinacms/src/components/media/media-item.tsx
> +      return <video src={item.previewSrc} />
I'm wondering if its a good idea to try and use the actual videos as the preview src. We may just want to use an icon.

2021-07-22 16:44 UTC, closed without merging