Allow 'useFormScreenPlugin' to take a second argument
tinacms/tinacms pull request #1703
Opened 2021-01-23 20:36 UTC by joeinnes

Adds an optional second argument to 'useFormScreenPlugin' to allow an icon to be passed to GlobalFormPlugin when instantiating a new Form Screen.

2021-01-24 09:16 UTC, zenflow commented
@joeinnes The `GlobalFormPlugin` constructor also has a third argument: `layout?: "fullscreen" | "popup"`.

I think it would make sense to, at the same time, add this argument to `useFormScreenPlugin` too.

I would frame the root issue as "some options for `GlobalFormPlugin` can't be passed through `useFormScreenPlugin`".

In my case I really needed to change the layout from 'popup' to 'fullscreen' (because of an issue where the height of the popup was too small) and it took me a while to realize (by digging into TinaCMS code) that instead of using `useFormScreenPlugin` I could use `GlobalFormPlugin` directly (e.g. `const plugin = useMemo(() => new GlobalFormPlugin(form, SettingsIcon, "fullscreen"), [form]);`).

2021-01-24 09:18 UTC, zenflow commented on packages/tinacms/src/react-tinacms/use-form.ts
> +export function useFormScreenPlugin(form: Form, icon?: any) {
```suggestion
export function useFormScreenPlugin(form: Form, icon?: any, layout?: "fullscreen" | "popup")) {
```

2021-01-24 09:19 UTC, zenflow commented on packages/tinacms/src/react-tinacms/use-form.ts
> +    return new GlobalFormPlugin(form, icon)
```suggestion
    return new GlobalFormPlugin(form, icon, layout)
```

2021-01-24 09:50 UTC, joeinnes commented
Absolutely right, I hadn't considered the layout option.

2021-01-24 10:37 UTC, zenflow commented
@joeinnes Awesome! Don't forget to update the PR title. 😃

2021-01-24 10:55 UTC, joeinnes commented
> @joeinnes Awesome! Don't forget to update the PR title. 😃

Done. Thanks!

2021-01-25 17:14 UTC, dwalkr requested changes

2021-01-25 17:14 UTC, dwalkr commented on packages/tinacms/src/react-tinacms/use-form.ts
>    }, [form])
```suggestion
  }, [form, icon, layout])
```

2021-01-26 12:09 UTC, DirtyF reviewed
Docs will need to be updated:
https://tina.io/docs/plugins/screens/#useformscreenplugin

2021-01-26 13:02 UTC, joeinnes commented
tinacms/tinacms.org#786 opened for docs.

2021-02-01 15:25 UTC, dwalkr approved these changes

2021-02-01 15:25 UTC, merged

2021-02-01 16:08 UTC, dwalkr commented
@all-contributors add @joeinnes for code