Ensure `null` values aren't passed back from getStaticPropsForTina
tinacms/tinacms pull request #2010
Opened 2021-08-06 21:22 UTC by jeffsee55

Closes https://github.com/tinacms/tinacms/issues/2009

2021-08-06 22:42 UTC, DirtyF approved these changes
LGTM

2021-08-09 12:52 UTC, jamespohalloran requested changes

2021-08-09 12:52 UTC, jamespohalloran commented on .changeset/odd-ducks-raise.md
> +Ensure `null` values aren't passed back from getStaticPropsForTina
```suggestion
Ensure `undefined` values aren't passed back from getStaticPropsForTina
```
According to the error I got, "null" is fine, but undefined causes the problems:

> Error: Error serializing .variables returned from getStaticProps in "/projects".
Reason: undefined cannot be serialized as JSON. Please use null or omit this value.

2021-08-09 19:58 UTC, jamespohalloran approved these changes

2021-08-10 16:54 UTC, dwalkr approved these changes

2021-08-10 16:54 UTC, merged