2464 - Integrates Chrome Components with TinaAdmin
tinacms/tinacms pull request #2506
Opened 2022-01-27 18:51 UTC by Enigmatical

As part of our push to unify the Sidebar experience with TinaAdmin, TinaAdmin will now make use of _some_ of the Sidebar's elements (mostly just the `Nav`).

Additional work has been done to match the UI feel from the demo website with actual TinaAdmin.

2022-01-27 19:11 UTC, Enigmatical commented
#### Remaining Punchlist:
- [ ] Address the multiple form bug that Logan and I found: https://github.com/tinacms/tinacms/issues/2505
- [ ] Add a triple-dot sub-menu to each list item (for "View", "Edit in Admin" (later), and "Delete" (later)
- [ ] Provide support for `RouteMapper`
  - For this phase, we'll just tuck the "View in Website" link inside a triple-dot sub-menu on each list item
  - Next phase, we'll actually link to the pages via the main link
- [ ] Fix the `ScreenPage` for `_type: screen` plugins based on `layout`

2022-01-27 19:14 UTC, Enigmatical commented on packages/@tinacms/toolkit/src/index.ts
> +export { Nav } from './packages/react-sidebar'
This is the only component that needs to be exported to `TinaAdmin`.  The rest of the `Sidebar` (and its context) are not necessary.

2022-01-27 19:17 UTC, Enigmatical commented on packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx
> +  }>
The majority of the changes to `Nav` are based around these new props.  I effectively decoupled `Nav` from `SidebarContext`, freeing me from having to maintain `SidebarContext` in the other place I wanted to use `Nav`.

Instead, I pass in the behaviors that I want `Nav` to use.

2022-01-27 19:35 UTC, Enigmatical commented on packages/tinacms/src/auth/TinaCloudProvider.tsx
> +  }
Register the `admin` API alongside the `tina` one for making calls to `TinaAdminApi` (specifically for `fetchCollections()` in the `Nav`).

2022-02-01 23:53 UTC, jeffsee55 requested changes
This looks awesome! Feels really good. I'll put some wishlist-type of items over on the next phase's issue https://github.com/tinacms/tinacms/issues/2530 so just a couple of small comments here

2022-02-01 23:53 UTC, jeffsee55 commented on packages/tinacms/src/auth/TinaCloudProvider.tsx
> +  }
I realize we've been doing this with `setupMedia,` but should this be inside `useMemo`?

2022-02-01 23:53 UTC, jeffsee55 commented on packages/tinacms/src/admin/pages/CollectionListPage.tsx
> +                    <Menu.Item>
Looks like we need a `key` here, guessing `item.label` would suffice

2022-02-02 17:29 UTC, jeffsee55 commented on packages/tinacms/src/auth/TinaCloudProvider.tsx
> +    setupAdmin()
I know we're doing the same thing with `setupMedia`, but should this be inside a `useMemo` hook?

2022-02-02 18:35 UTC, jeffsee55 submitted a review, later dismissed

2022-02-02 18:37 UTC, jeffsee55 approved these changes

2022-02-02 19:38 UTC, merged