Add an MDX field to the CLI init example.
tinacms/tinacms pull request #2720
Opened 2022-03-21 19:45 UTC by mittonface

Closes #2641 

This PR adds a simple MDX field to the example you get when you run `@tinacms/cli init`.

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/5082908/159351397-9fee45c0-bbad-49f0-acd0-a3e82fc6d2f6.png">

Nothing extremely beautiful. I considered pulling in the `CallOut` component that we have in some docs and blog posts but didn't want to add in that much boilerplate. But happy to make the component a bit more exciting it that seems desirable.

1. To test this I've been starting with a next-js starter `npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"`
2. Then you can use a dev version that I've pushed to npm `npx @tinacms/cli@0.0.0-2022221193751 init`

2022-03-21 19:46 UTC, mittonface commented on packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
> -                content={window.marked.parse(data.getPostsDocument.data.body)}
Somewhat uncertain about the removal of this. But this is what I needed to do to make it work. 

Let me know if this is fine.

2022-03-22 13:34 UTC, logan-anderson commented on packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
>    // Use the props returned by get static props (this can be deleted when the edit provider and tina-wrapper are moved to _app.js)
This comment can probably be removed or updated

2022-03-22 13:48 UTC, logan-anderson requested changes
Looks good! it is all working as expected. The only other thing that should be done [is remove the `<script>`  tag](https://github.com/tinacms/tinacms/blob/8c23d69a2fa385d2c31b906b732b835f9a93b737/packages/%40tinacms/cli/src/cmds/init/setup-files/index.ts#L121) for the marked CDN as it is no longer needed (Tailwind is still needed though)

2022-03-22 15:12 UTC, dwalkr approved these changes

2022-03-22 15:40 UTC, logan-anderson approved these changes

2022-03-22 15:41 UTC, merged