Don't restart vite server on every schema change
tinacms/tinacms pull request #3318
Opened 2022-10-26 22:53 UTC by jeffsee55

2022-10-27 18:07 UTC, logan-anderson commented
@jeffsee55 When I save a file and the GQL server restarts I get a white screen and can not view the admin.

https://www.loom.com/share/9aa26c35560b44eaa06026a65d3c6aed

2022-10-27 18:09 UTC, jeffsee55 commented
@logan-anderson I think this also needs to not clear out the `app/prebuild` folders in that reset logic. I'll update this PR on top of main now that that's merged and remove those two from the cleanup logic

2022-10-28 11:27 UTC, logan-anderson approved these changes

2022-10-28 11:32 UTC, logan-anderson requested changes
Getting this Error when starting the server @jeffsee55 
![Screen Shot 2022-10-28 at 7 32 09 AM](https://user-images.githubusercontent.com/43075109/198577585-27bc9375-77e3-4c36-855e-91b8bd789df8.png)

2022-10-28 16:17 UTC, logan-anderson approved these changes

2022-10-28 16:46 UTC, merged