Added a onLogin callback
tinacms/tinacms pull request #3422
Opened 2022-11-24 15:59 UTC by logan-anderson

This PR adds an onLogin that is needed to add Nextjs preview mode.

See changset for implementation.

2022-11-29 22:34 UTC, jeffsee55 requested changes
Probably best to demo this for office hours but looks good to me! Just a leftover `console.log` to remove

2022-11-29 22:34 UTC, jeffsee55 commented on packages/tinacms/src/internalClient/index.ts
> +    console.log({ schema: options?.schema })
```suggestion
```

2022-11-30 14:30 UTC, logan-anderson commented
> Probably best to demo this for office hours but looks good to me! Just a leftover `console.log` to remove

Removed them

2022-11-30 18:05 UTC, jeffsee55 approved these changes

2022-11-30 18:05 UTC, merged