Fix issue resolving alias fields when passing through the `useTina` hook
tinacms/tinacms pull request #3427
Opened 2022-11-29 22:12 UTC by jeffsee55

2022-11-29 22:26 UTC, jeffsee55 commented
This PR introduced a query that we didn't support, that should now be working with this PR - https://github.com/tinacms/tina.io/pull/1440

2022-11-30 13:06 UTC, jamespohalloran requested changes

2022-11-30 13:06 UTC, jamespohalloran commented on packages/@tinacms/app/appFiles/src/lib/machines/query-machine.ts
> +          console.log(newData)
```suggestion
```

2022-11-30 13:20 UTC, jamespohalloran approved these changes

2022-11-30 13:20 UTC, merged