License update
tinacms/tinacms pull request #3577
Opened 2023-02-03 18:23 UTC by jamespohalloran

Updated license

2023-02-03 19:07 UTC, logan-anderson commented
@jamespohalloran IS there any way you could pull the changes in `kldavis4/poc/abstract_level_store` instead of main?

2023-02-03 19:12 UTC, logan-anderson commented
@jamespohalloran Looks like there is some conflicts. Mind if I take a stab at resolving them?

2023-02-03 20:49 UTC, kldavis4 approved these changes

2023-02-06 14:50 UTC, logan-anderson requested changes
@jamespohalloran  Looks some some unrelated changes got into this PR. Mind taking a look at this one? https://github.com/tinacms/tinacms/pull/3580

2023-02-06 14:54 UTC, logan-anderson commented
Closing in favour of #3580

2023-02-06 14:54 UTC, closed without merging