fix: previous directory link in Tina MediaManager
tinacms/tinacms pull request #3660
Opened 2023-03-03 12:13 UTC by coreyaus

## Bug description:

- Previously the `dirname` function had a return value of type `RegExpMatchArray | null` - the result of calling `String.prototype.match()`
- However the `prevDir` variable must be of type `string` (or undefined or null) as it is passed directly to the `setDirectory` function
- Previously the media manager crashed when clicking the back link and threw a `TypeError` with the message `directory.replace is not a function` (given you can't call `replace` on a `RegExpMatchArray`)
- This fix extends the regex in the `dirname` function to use a capturing group and ensure it always returns a `string` or `undefined`

2023-03-03 12:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tinacms/tinacms?pullRequest=3660) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tinacms/tinacms?pullRequest=3660) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tinacms/tinacms?pullRequest=3660) it.</sub>

2023-03-03 14:20 UTC, logan-anderson commented
@coreyaus Thanks for the contribution.  Do you minding singing or [Contributor License Agreement](https://cla-assistant.io/tinacms/tinacms?pullRequest=3660)?

Thanks!

2023-03-04 06:09 UTC, coreyaus commented
Thanks @logan-anderson - a pleasure 😄  I've just signed the CLA - let me know if you need anything else from me. Have a top weekend and all the best with the work you and the team are doing!

2023-03-06 14:49 UTC, logan-anderson requested changes
@coreyaus Do you mind adding a changset? This can be done by going to root of the repo, running `pnpm changeset` and then following the instructions. Please make sure this is a patch change (not a minor or a major). 

Code looks good! I will approve and merge after the changset is added. Thanks again @coreyaus .

2023-03-06 19:11 UTC, jamespohalloran commented
@logan-anderson Just pushed a changeset for this

2023-03-06 19:25 UTC, jamespohalloran approved these changes

2023-03-06 19:25 UTC, merged

2023-03-15 19:05 UTC, coreyaus commented
Hi team - Sorry for the delayed response! I only saw the request to add a changeset after one had already been created. I'll read the full contribution guidelines next time and do a better job of following the process for any future tweaks. Thanks for finalising this and incorporating it in the tool. Cheers, and have a lovely week!