Add skip client to forestry configs
tinacms/tinacms pull request #3734
Opened 2023-03-23 19:30 UTC by jeffsee55

2023-03-27 18:26 UTC, jamespohalloran requested changes

2023-03-27 20:29 UTC, jeffsee55 commented on packages/@tinacms/app/src/Playground.tsx
> +              ? 'No autoqueries found, the Tina config is likey set to client.skip = true. Learn about how to generate autoqeries.'
```suggestion
              ? 'No auto-generated queries found, the Tina config is likely set to client.skip = true'
```

2023-03-27 20:29 UTC, jeffsee55 commented on packages/@tinacms/app/src/Playground.tsx
> +              ? 'No autoqueries found, the Tina config is likey set to client.skip = true. Learn about how to generate autoqeries.'
Yeah sorry I thought I fixed that. The link is included in the `Learn more here` tag below.

2023-03-27 20:30 UTC, jeffsee55 commented on packages/@tinacms/app/src/Playground.tsx
>                : "Tina's autogenerated queries can be found here as well as any queries you may have defined yourself."}{' '}
```suggestion
              : "Tina's auto-generated queries can be found here as well as any queries you may have defined yourself."}{' '}
```

2023-03-28 16:33 UTC, logan-anderson commented
Looks good to me other then that small comment I had. Looks like there is some conflicts with main but other then that looks good.

2023-03-28 17:55 UTC, merged