Recreate GithubBridge to support separate content repos in self-hosted projects
tinacms/tinacms pull request #3936
Opened 2023-05-15 04:53 UTC by coreyaus

## Summary

- This adds a `GithubBridge` in order to better support separate content repositories for self-hosted projects
- This will also help provide a path to better support reindexing for self-hosted project (i.e. keeping the data layer updated when changes are pushed directly via git, rather than made through the Tina UI)

It draws heavily from the original `GithubBridge` that previously existed - i.e. [this historical file](https://github.com/tinacms/tinacms/blob/930260c839cbd1908e9e6902734c94f6d64d3282/packages/%40tinacms/datalayer/src/database/bridge/github.ts) that was removed in [this commit](https://github.com/tinacms/tinacms/commit/fb74f4a129164e3b40ff7cd38928682dadab945c)

## Background

- See the excellent information @logan-anderson provided in this discussion thread: https://github.com/tinacms/tinacms/discussions/3589#discussioncomment-4960323
- And the further details in this issue: https://github.com/tinacms/tinacms/issues/3609, including this video overview of the key components to consider: https://www.loom.com/share/c7d1c4f5bda04ec3a1dacff2a03efac1

2023-05-16 04:24 UTC, Perni1984 commented
@coreyaus many thanks for putting this together, it will help us a lot as we're currently struggling with this topic.

2023-05-16 16:44 UTC, logan-anderson requested changes
Hey @coreyaus changes look good! Thanks for this. Just one small thing. Can the `GithubBridge` be moved to its own package?

This is so that folks who are not using it do not have to install @octokit/rest.

The package could be named `@tinacms/github-bridge`

If you don't want to move it we would be happy to (it just could take a bit as we are working on some other things at the momant ).

If you want to do this yourself feel free. The general steps are
1. Create a new folder called `packages/@tinacms/github-bridge`
2. Copy the package.json from `@tinacms/graphql` and remove all deps that are not needed. Make sure to keep `@tinacms/scripts`, `typescript` and `jest`. 
3. update the version in the package.json to 0.0.1 and the name to  `@tinacms/github-bridge` 
4. Create a `src/index.ts` file and add github bridge to it

2023-05-17 12:19 UTC, coreyaus commented
Thanks for the quick review @logan-anderson and great to hear it'll be useful @Perni1984!

That makes sense about moving this to its own package to avoid the `@octokit/rest` dependency for users who don't need it - I'm definitely happy to give that a go and should hopefully be able to take a look at it this weekend 👍 I'll post an update when there's a revised version you can look at, or if I have any questions along the way.

Cheers gents, and have a great day!

2023-09-07 21:32 UTC, coreyaus commented
Thanks for the early feedback and guidance on this PR. The `github-bridge` worked well but the main issue I ran into when I created it a couple of months ago was that handling the sync to GitHub via the `put` function in the `github-bridge` made the `onPut` and `onDelete` handlers in the `database.ts` file redundant. When I initially ran the tinacms build from this PR locally in my test project I saw 2 commits for each saved change - the commit with the changes made by the `github-bridge` and an empty commit made via the `onPut` handler in the `database.ts` file.

To be honest I thought I'd written at the time to get feedback on how to handle that behaviour but obviously dreamt that so apologies I didn't provide an update earlier! I've been following some of the recent draft PRs related to self-hosting improvements (e.g. #4095 and #4106). It looks like those will address that point above and also add a bunch of powerful features so I will close this PR now, given it will be superseded when #4106 is merged to `main`

Let us know if there's any useful way we can contribute to that current work on self-hosted improvements (e.g. testing, docs, etc). In the meantime l'll give the latest code on the `feat/self-hosted-improvements` branch a spin locally - looks like that's possible by installing version `0.0.0-20230901181730` of the core packages.

Happy Friday, and thanks for all the epic work you're doing!

2023-09-07 21:32 UTC, closed without merging

2023-12-01 13:08 UTC, coreyaus commented
Hey all - just a quick follow up that now that the latest self-hosting features have been officially launched I've created a new PR around this same concept of re-introducing the GitHubBridge to support self-hosted repositories with separate content repositories. See the full details in PR #4384. Happy Friday!