Fix toolbar item cms
tinacms/tinacms pull request #5004
Opened 2024-10-04 02:16 UTC by Ben0189

#4795 

Fix toolbar floating icon bug in rich text editor using container query in tailwind

2024-10-04 04:09 UTC, Jord-Gui approved these changes

2024-10-04 04:29 UTC, Jord-Gui requested changes
Fix resizing

2024-10-04 04:56 UTC, Ben0189 commented
Done fixing the resizing calculation, we will now safe from any width bug in the toolbar

2024-10-04 05:06 UTC, Jord-Gui requested changes
There's a small bug where the three dots pop up even though there isn't anything to hide
<img width="568" alt="image" src="https://github.com/user-attachments/assets/7d17a264-4827-4959-829d-7a3ebd0a5d73">

2024-10-04 06:27 UTC, Ben0189 commented
✅ Done fix - previous calculation does not take in consideration when embed button is not show 🥲 (now solved)

2024-10-04 07:25 UTC, JackDevAU commented on packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/fixed-toolbar-buttons.tsx
> +    const paragraphIconWidth = width < MD_BREAKPOINT ? 58 : 128
should we add these floating numbers into variables?

2024-10-10 05:07 UTC, Ben0189 commented
I had also refactor the width calculation function so it is now easier to add plugin without breaking the width again

2024-10-10 05:31 UTC, Jord-Gui approved these changes

2024-10-10 05:31 UTC, merged